//! RFB's own event types.
//!
//! The geometry these carry belongs to [`crate::remote`]: it is the same on every
//! wire. What stays here is RFB-shaped -- the wire form of a screen, the events the
//! decoder produces, and the fence flags.

use crate::remote::{Key, Pointer, Rect, ResizeStatus, Screen, ScreenInfo, ScreenLayout};
use crate::rfb::PixelFormat;
use crate::rfb::client::clipboard::Caps as ClipboardCaps;

type ImageData = Vec<u8>;

impl ResizeStatus {
    /// The status codes an `ExtendedDesktopSize` rectangle carries, which are RFB's
    /// own numbering and mean nothing on another wire.
    pub fn from_wire(code: u16) -> Self {
        match code {
            0 => ResizeStatus::Success,
            1 => ResizeStatus::Prohibited,
            2 => ResizeStatus::OutOfResources,
            3 => ResizeStatus::InvalidLayout,
            4 => ResizeStatus::Forwarded,
            other => ResizeStatus::Unknown(other),
        }
    }
}

impl ScreenInfo {
    /// Bytes one screen takes in `ExtendedDesktopSize` and `SetDesktopSize`.
    pub const WIRE_LEN: usize = 16;

    pub fn encode(&self, out: &mut Vec<u8>) {
        out.extend_from_slice(&self.id.to_be_bytes());
        out.extend_from_slice(&self.x.to_be_bytes());
        out.extend_from_slice(&self.y.to_be_bytes());
        out.extend_from_slice(&self.width.to_be_bytes());
        out.extend_from_slice(&self.height.to_be_bytes());
        out.extend_from_slice(&self.flags.to_be_bytes());
    }

    pub fn decode(buf: &[u8; Self::WIRE_LEN]) -> Self {
        Self {
            id: u32::from_be_bytes(buf[0..4].try_into().unwrap()),
            x: u16::from_be_bytes(buf[4..6].try_into().unwrap()),
            y: u16::from_be_bytes(buf[6..8].try_into().unwrap()),
            width: u16::from_be_bytes(buf[8..10].try_into().unwrap()),
            height: u16::from_be_bytes(buf[10..12].try_into().unwrap()),
            flags: u32::from_be_bytes(buf[12..16].try_into().unwrap()),
        }
    }
}

type SrcRect = Rect;
type DstRect = Rect;

/// Events generated by the [crate::rfb::VncClient]
#[non_exhaustive]
#[derive(Debug, Clone)]
pub enum VncEvent {
    /// Tell the client how to display the images.
    ///
    /// May be received more than once.
    SetResolution(Screen),
    /// Sent when the connector was not given a pixel format, to tell the client
    /// how to interpret image data.
    SetPixelFormat(PixelFormat),
    /// Raw image data, in the order given by the pixel format.
    RawImage(Rect, ImageData),
    /// Copy image data from the second rect to the first.
    Copy(DstRect, SrcRect),
    /// A JPEG image, from a Tight rectangle.
    JpegImage(Rect, ImageData),
    /// Generated when [crate::rfb::VncEncoding::CursorPseudo] is negotiated.
    ///
    /// See [RFC6143, section-7.8.1](https://www.rfc-editor.org/rfc/rfc6143.html#section-7.8.1).
    /// Carried for completeness: this client does not request the encoding yet,
    /// so the server draws the pointer into the framebuffer instead.
    #[allow(dead_code)]
    SetCursor(Rect, ImageData),
    /// The desktop layout, from the `ExtendedDesktopSize` pseudo-encoding.
    ///
    /// Receiving one of these at all is how a client learns the server supports
    /// `SetDesktopSize`.
    DesktopLayout(ScreenLayout),
    /// Every rectangle of a `FramebufferUpdate` has been consumed.
    ///
    /// This is what lets a client pace requests instead of firing them on a
    /// timer: ask for the next update here, and never have more than one
    /// outstanding.
    FramebufferUpdateEnd,
    /// Just ring a bell.
    Bell,
    /// The server's clipboard, as text.
    ///
    /// From a legacy `ServerCutText`, which is Latin-1 only per
    /// [RFC6143](https://www.rfc-editor.org/rfc/rfc6143.html#section-7.6.4), or from
    /// an extended clipboard `provide`, which is UTF-8. By the time it is an event the
    /// difference is spent: either way this is the remote clipboard.
    Text(String),
    /// What the server will accept on the extended clipboard.
    ///
    /// A server must send this in answer to a `SetEncodings` naming the
    /// `ExtendedClipboard` pseudo-encoding, so it arriving is how the extension is
    /// discovered -- and nothing extended may be sent before it does.
    ClipboardCaps(ClipboardCaps),
    /// The server's clipboard changed, without saying what is on it.
    ///
    /// `text` is false when the remote clipboard went empty. Fetching the text takes a
    /// [`X11Event::ClipboardRequest`], which is what makes a remote selection cost
    /// nothing until somebody wants it.
    ClipboardNotify { text: bool },
    /// The server wants the clipboard we announced, and is asking for it now.
    ClipboardRequest,
    /// The server's lock-key state changed.
    ///
    /// Worth having because a remote caps lock that disagrees with the local one
    /// makes every keystroke come out in the wrong case.
    LedState {
        /// Decoded for completeness; no terminal reports its own scroll lock, so
        /// there is nothing to compare it against.
        #[allow(dead_code)]
        scroll: bool,
        num: bool,
        caps: bool,
    },
    /// The server is no longer pushing updates unasked.
    ///
    /// Also how support is discovered: a server sends this the first time it sees
    /// `ContinuousUpdates` in `SetEncodings`.
    EndOfContinuousUpdates,
    /// A synchronisation point from the server, to be echoed back.
    Fence { flags: u32, payload: Vec<u8> },
    /// An error from the async routines, propagated to the current context.
    Error(String),
}

/// Fence flag bits, from the RFB `ClientFence` definition.
pub mod fence {
    pub const BLOCK_BEFORE: u32 = 1 << 0;
    pub const BLOCK_AFTER: u32 = 1 << 1;
    /// Not honoured: it asks the server to hold the *next* update until the fence is
    /// answered, and we filter it out of a response rather than pretend to implement
    /// it. Named so the filter reads clearly.
    #[allow(dead_code)]
    pub const SYNC_NEXT: u32 = 1 << 2;
    pub const REQUEST: u32 = 1 << 31;
}

/// Client-side events, asking the engine to send something to the server.
#[non_exhaustive]
#[derive(Debug, Clone)]
pub enum X11Event {
    /// Ask for an incremental frame update.
    Refresh,
    /// Ask for a full, non-incremental frame update.
    ///
    /// Also the only way to learn the server's current screen layout: a server
    /// supporting `ExtendedDesktopSize` must answer a non-incremental request
    /// with a layout rectangle.
    FullRefresh,
    /// Key down or up.
    KeyEvent(Key),
    /// Mouse move, button or scroll.
    PointerEvent(Pointer),
    /// Send text to the server's clipboard, the legacy way. Latin-1 only.
    CopyText(String),
    /// Ask the server for the clipboard it announced with
    /// [`VncEvent::ClipboardNotify`].
    ClipboardRequest,
    /// Tell the server we hold text, without sending it.
    ///
    /// The server asks for it with [`VncEvent::ClipboardRequest`] if and when
    /// something on the remote side pastes.
    ClipboardNotify,
    /// Send text to the server's clipboard over the extended clipboard, in UTF-8.
    ///
    /// Only legal once [`VncEvent::ClipboardCaps`] has said the server takes a
    /// `provide`, and unsolicited only within the size it advertised.
    ClipboardProvide(String),
    /// Ask the server to start or stop pushing updates without being asked.
    ///
    /// Only legal once the server has sent `EndOfContinuousUpdates`, which is its
    /// way of saying the extension exists.
    EnableContinuousUpdates { enable: bool, rect: Rect },
    /// Answer a `ServerFence`, or start a synchronisation of our own.
    Fence { flags: u32, payload: Vec<u8> },
    /// Ask the server to change its framebuffer size.
    ///
    /// Only legal once a [`VncEvent::DesktopLayout`] has arrived, and the screen
    /// ids and flag bits from that layout have to be carried over.
    SetDesktopSize {
        width: u16,
        height: u16,
        screens: Vec<ScreenInfo>,
    },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn screen_info_round_trips_through_the_wire_format() {
        let info = ScreenInfo {
            id: 0xdead_beef,
            x: 1,
            y: 2,
            width: 1600,
            height: 833,
            flags: 0x8000_0001,
        };
        let mut buf = Vec::new();
        info.encode(&mut buf);
        assert_eq!(buf.len(), ScreenInfo::WIRE_LEN);
        assert_eq!(
            buf,
            vec![
                0xde, 0xad, 0xbe, 0xef, // id
                0x00, 0x01, // x
                0x00, 0x02, // y
                0x06, 0x40, // width  = 1600
                0x03, 0x41, // height = 833
                0x80, 0x00, 0x00, 0x01, // flags
            ]
        );
        let bytes: [u8; ScreenInfo::WIRE_LEN] = buf.try_into().unwrap();
        assert_eq!(ScreenInfo::decode(&bytes), info);
    }

    #[test]
    fn resize_status_codes_match_the_spec() {
        assert_eq!(ResizeStatus::from_wire(0), ResizeStatus::Success);
        assert_eq!(ResizeStatus::from_wire(1), ResizeStatus::Prohibited);
        assert_eq!(ResizeStatus::from_wire(2), ResizeStatus::OutOfResources);
        assert_eq!(ResizeStatus::from_wire(3), ResizeStatus::InvalidLayout);
        assert_eq!(ResizeStatus::from_wire(4), ResizeStatus::Forwarded);
        assert_eq!(ResizeStatus::from_wire(99), ResizeStatus::Unknown(99));
    }
}
